#!/bin/bash
# Skill: Daily Digest — summarize today's agent activity
# Usage: ./run.sh [YYYY-MM-DD]

set -euo pipefail

SEED_HOME="${SEED_HOME:-$(cd "$(dirname "$0")/../../.." && pwd)}"
TARGET_DATE="${1:-$(date +%Y-%m-%d)}"
DATE_SHORT=$(echo "$TARGET_DATE" | tr -d '-')
LOG_DIR="$SEED_HOME/logs"

echo "# Daily Digest — $TARGET_DATE"
echo ""

# Count cycles
CYCLE_COUNT=$(ls -1 "$LOG_DIR"/cycle-${DATE_SHORT}*.log 2>/dev/null | wc -l)
echo "## Activity"
echo "- **Cycles**: $CYCLE_COUNT"

# Count inbox messages processed
if [ -d "$SEED_HOME/messages/inbox" ]; then
    INBOX_COUNT=$(find "$SEED_HOME/messages/inbox" -name "*.json" -newer "$LOG_DIR" 2>/dev/null | wc -l)
    echo "- **Messages processed**: ~$INBOX_COUNT"
fi

echo ""
echo "## Cycle Summaries"
for log in "$LOG_DIR"/cycle-${DATE_SHORT}*.log; do
    [ -f "$log" ] || continue
    CYCLE_NAME=$(basename "$log" .log)
    DURATION=$(grep -oP '\d+s\)' "$log" | tail -1 || echo "?s)")
    echo "- $CYCLE_NAME ($DURATION"
done

echo ""
echo "*Generated by daily-digest skill*"
